//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FIlmApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class film
    {
        public int Id { get; set; }
        public string FilmName { get; set; }
        public string Desctiption { get; set; }
        public string Director { get; set; }
        public string Creator { get; set; }
        public string Year { get; set; }
        public string ImageUrl { get; set; }
    }
}
